// Code generated by kratos tool genmc. DO NOT EDIT.

/*
  Package dao is a generated mc cache package.
  It is generated from:
  type _mc interface {
		// mc: -key=keyArt -type=get
		CacheToken(c context.Context, id int64) (*vrfapi.Token, error)
		// mc: -key=keyArt -expire=d.demoExpire
		AddCacheToken(c context.Context, id int64, art *vrfapi.Token) (err error)
		// mc: -key=keyArt
		DeleteTokenCache(c context.Context, id int64) (err error)
	}
*/

package dao

import (
	"context"
	"fmt"

	"github.com/bilibili/kratos/pkg/cache/memcache"
	"github.com/bilibili/kratos/pkg/log"
	vrfapi "verify/api"
)

var _ _mc

// CacheToken get data from mc
func (d *dao) CacheToken(c context.Context, id int64) (res *vrfapi.Token, err error) {
	key := keyArt(id)
	res = &vrfapi.Token{}
	if err = d.mc.Get(c, key).Scan(res); err != nil {
		res = nil
		if err == memcache.ErrNotFound {
			err = nil
		}
	}
	if err != nil {
		log.Errorv(c, log.KV("CacheToken", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// AddCacheToken Set data to mc
func (d *dao) AddCacheToken(c context.Context, id int64, val *vrfapi.Token) (err error) {
	if val == nil {
		return
	}
	key := keyArt(id)
	item := &memcache.Item{Key: key, Object: val, Expiration: d.demoExpire, Flags: memcache.FlagJSON}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheToken", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// DeleteTokenCache delete data from mc
func (d *dao) DeleteTokenCache(c context.Context, id int64) (err error) {
	key := keyArt(id)
	if err = d.mc.Delete(c, key); err != nil {
		if err == memcache.ErrNotFound {
			err = nil
			return
		}
		log.Errorv(c, log.KV("DeleteTokenCache", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}
